# Site settings
title: stealthpuppy
author: Aaron Parker
email: aaron@stealthpuppy.com
description: >- # this means to ignore newlines until "baseurl:"
  Aaron Parker, Citrix Technology Professional & Principal Modern Workplace Architect @Insentra, on End User Computing and Enterprise Mobility
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stealthpuppy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stealthpuppy
github_username:  aaronparker

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-archives
#  - jekyll-avatar
#  - jekyll-paginate

show_excerpts: true
# paginate: 10

disqus:
  shortname: stealthpuppy

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    twitter: stealthpuppy
    github:  aaronparker
    rss: rss
    linkedin: aaronedwardparker

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - smb-not-cifs.md

# Jekyll Archives
jekyll-archives:
  enabled:
  - categories
  # - tags
  - year
  layouts:
    year: archives-year
    category: archives
    tag: archives
  permalinks:
    year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    # tag: '/tag/:name/'
    category: '/category/:name/'

# _config.yml
algolia:
   application_id: UBLG1JVFAS
   index_name: stealthpuppy
   search_only_api_key: 94e7fce0796e173301d44f2b69657fdc
