# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: stealthpuppy
email: aaron@stealthpuppy.com
description: >- # this means to ignore newlines until "baseurl:"
  on end user computing and enterprise mobility
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stealthpuppy
github_username:  aaronparker

# name: "Affiliates Theme for Jekyll"
# meta_description: "Jekyll theme for blogging."
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/favicon.ico'
paginate: 12
# google_analytics: ''
# disqus: ''
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-cayman
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Authors
authors:
  aaronparker:
    name: Aaron Parker
    display_name: Aaron Parker
    gravatar: 914255233cb1be4dea2225535ab92959
    email: aaron@stealthpuppy.com
    web: https://stealthpuppy.com/
    twitter: https://twitter.com/stealthpuppy
    description: "Solution architect, End-user computing and enterprise mobility specalist. Citrix Technology Professional."

# List of links in the navigation bar
navbar-links:
  About: "about"
  Projects:
    - VcRedist: "https://docs.stealthpuppy.com/docs/vcredist/"
    - LatestUpdate: "https://docs.stealthpuppy.com/docs/latestupdate/"
    - SMB not CIFS: "https://stealthpuppy.com/smb-not-cifs/"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/media/stealthpuppy.png"
